package com.bestbudz.core.task.impl;

public enum TaskIdentifier {
  CURRENT_ACTION,
  SKULL,
  PROFESSION_RESTORE,
  SPECIAL_RESTORE,
  RUN_ENERGY,
  PROFESSION_LOCK,
  PET_HUNGER,
  BONES_ON_ALTER,
  CULTIVATION,
  TZHAAR,
  FISHER,
  CHARACTER_BACKUP,
  PROFESSION_CREATING,
  PYRAMID_PLUNDER,
  TREASURE_TRAILS,
  QUARRYING_ROCK,
  WOOD_ON_FIRE,
  WEED_WITH_BUD
}
