package com.bestbudz.core.discord.stonerbot.config;

public class DiscordBotSpeech {
	public static String[] statusMessages = {
		"grinding harder than my kief catcher on a friday night",
		"jaybane's got me leveling up in ways i never imagined",
		"this learning curve got me more twisted than my backwoods",
		"playing so long my joint turned into historical evidence",
		"my skills are as fire as my current strain selection",
		"leveling up in game and consciousness simultaneously",
		"the grind is real but the vibes are realer",
		"been playing so long my pizza guy knows my exact coordinates",
		"sessions longer than my tolerance breaks... that's dedication",
		"only game that truly gets my stoner logic",
		"my k/d ratio matches my thc percentage... coincidence?",
		"been grinding since my last dispensary run went south",
		"why did the stoner cross the road? dispensary was closed... he didn't",
		"my dealer texted 'u up?' at 3am... obviously bro, gaming time",
		"tried to roll a joint left-handed... looked like modern art",
		"my smoke detector thinks i'm a walking fire hazard",
		"spent 20 minutes looking for my phone while on a call",
		"my munchies evolved and now have their own grocery budget",
		"tried unlocking my car with house keys for 10 straight minutes",
		"tolerance break lasted exactly one dankrupt day",
		"accidentally hotboxed my uber... driver left a 5-star review",
		"joint rolling skills peaked at 'functional disaster' level",
		"cotton mouth so bad i'm drinking pickle juice unironically",
		"my dealer's snap score is higher than me... barely",
		"tried smoking oregano once... 0/10 would not recommend",
		"lighter collection worth more than my crypto portfolio",
		"so blazed i put cereal in fridge, milk in pantry",
		"smoke ring game weaker than my will to leave this couch",
		"paid 60 for an eighth... it was oregano... again",
		"edibles kicked in during zoom meeting... awkward silence",
		"tried relighting an already lit joint... twice in one session",
		"my dealer vacations more than i do... highly suspicious",
		"so stoned i googled 'how to breathe manually'",
		"bong water cleaner than my browser history somehow",
		"called mom instead of dealer... she hung up first",
		"joint looks like it was rolled by parkinsonian octopus",
		"tried tipping pizza guy with monopoly money... he considered it",
		"smoke session soundtrack is just my stomach growling",
		"lit a joint with another joint... surprisingly effective method",
		"dealer said 'this is fire'... narrator: it wasn't",
		"so blazed i thanked alexa for simply existing",
		"tolerance higher than 2008 gas prices, somehow",
		"went to work accidentally high... productivity up 420%",
		"joint rolling technique: hope, prayer, and duct tape",
		"tried charging my grinder like a phone... logic unclear",
		"dealer's reliability inversely related to my sobriety levels",
		"attempted smoking a crayon... color me disappointed",
		"munchies developed their own credit score, apparently",
		"complimented my own mirror outfit while passing by",
		"smoke detector most judgmental thing in my house",
		"made gravity bong with fishbowl... fish were unamused",
		"dealer's 'be there in 5' means sometime this century",
		"tried saving my real life progress... unsuccessful",
		"joint resembles expensive, useless abstract art piece",
		"cotton mouth severe enough to consider iv fluids",
		"lighter has abandonment issues from constant disappearances",
		"apologized to furniture for my mere existence",
		"tolerance break shorter than my actual attention span",
		"ordered pizza to childhood address from 15 years ago",
		"smoke rings writing haikus in ancient aramaic",
		"tried petting my own reflection... seemed friendly",
		"dealer's math more creative than my life excuses",
		"rolled joint with papers... forgot the actual weed",
		"munchies achieved sentience, filed for independence",
		"tried scrolling down on physical book pages",
		"bong hit different after cleaning... literally everything",
		"accidentally hotboxed parents' house... they joined in",
		"joint rolling approaching 'toddler with mittens' skill level",
		"tried unlocking phone with debit card pin... repeatedly",
		"dealer's punctuality makes public transport look reliable",
		"smoked tea leaves... 2/10 relaxing but disappointing",
		"tolerance higher than credit score... significantly",
		"tried turning volume up on my sandwich",
		"smoke session has its own zip code now",
		"grocery shopped while high... bought 47 chip bags",
		"joint survived several apparent natural disasters",
		"tried rewinding a live conversation... didn't work",
		"dealer's 'top shelf' came from shoe bottom",
		"lit joint with phone flashlight... a for effort",
		"munchies developed stockholder rights in taco bell",
		"googled 'how to stop being high' while getting higher",
		"smoke detector has ptsd from my cooking attempts",
		"called dealer 'mom'... they actually answered to it",
		"joint rolling involves more hope than actual physics",
		"tried liking a comment in face-to-face conversation",
		"tolerance break lasted exactly one commercial break",
		"smoked oregano again... fool me twice, shame on... what?",
		"dealer's reliability like my sobriety: purely theoretical",
		"tried changing microwave channel... made sense then",
		"munchies developed their own customer loyalty program",
		"went to wrong dispensary... in completely wrong state",
		"joint looks like expensive, confusing modern art",
		"tried pausing real life for screenshot... unsuccessful",
		"smoke rings more organized than my entire life",
		"rolled joint with newspaper... got high on current events",
		"dealer's 'premium' is grandma's backyard herb garden",
		"unlocked house with car remote... logic was there",
		"tolerance higher than expectations... that's saying something",
		"ordered pizza in spanish... don't speak spanish",
		"joint rolling peaked at 'structurally questionable' level",
		"tried tipping uber driver with bitcoin... future thinking",
		"munchies achieved full corporate status, apparently",
		"smoked cigarette backwards... twice in one sitting",
		"dealer operates on geological time scales",
		"googled 'am i too high' while climbing higher",
		"smoke session has its own weather patterns",
		"went to church high... unexpectedly found religion",
		"joint assembled by caffeinated squirrels, apparently",
		"tried swiping left on bathroom mirror... muscle memory",
		"tolerance break interrupted by tuesday existing",
		"rolled joint with gift wrap... festive but ineffective",
		"dealer's 'fire' burns like birthday candle",
		"tried downloading more ram for my brain",
		"munchies unionized, demand better working conditions",
		"went to work on sunday... somehow got promoted",
		"joint rolling defies several laws of physics",
		"tried ctrl+z on my life choices... windows error",
		"smoke detector filed restraining order against me",
		"lit joint with magnifying glass... sophisticated caveman vibes",
		"dealer's punctuality makes waiting for godot seem punctual",
		"tried adjusting brightness on my food... seemed logical",
		"tolerance higher than student loans... barely",
		"ordered chinese in mandarin... got spanish fortune cookies",
		"joint looks like abstract expressionism's bad day",
		"tried skipping real life intro... no button found",
		"munchies developed their own cryptocurrency, somehow",
		"smoked joint in rain... learned humidity lesson",
		"dealer's 'exotic' strains more common than basic math",
		"googled 'how to ungoogle something'... paradox created",
		"smoke session achieved unesco world heritage status",
		"went to gym high... discovered muscles i forgot existed",
		"joint rolling like dance moves: enthusiastic but concerning",
		"tried pausing spotify on actual radio... confusion ensued",
		"tolerance break sabotaged by my own hands",
		"rolled joint with aluminum foil... space-age disappointment",
		"dealer operates on neptune time... day is 16 hours",
		"used google translate on my cat... results inconclusive",
		"munchies established diplomatic relations with my fridge",
		"went to dentist high... complimented my oral hygiene",
		"joint looks like picasso's interpretation of functional design",
		"tried zooming into real life with fingers... unsuccessful",
		"smoke rings writing bestselling novel, apparently",
		"smoked potpourri... smelled great, felt absolutely nothing",
		"dealer's 'premium indoor' grown in closet with desk lamp",
		"put car in airplane mode... seemed reasonable then",
		"tolerance higher than wifi signal... significantly more reliable",
		"tried to water my plastic plant... for three weeks",
		"dealer's 'two minutes away' operates on mars time",
		"googled 'why is my food cold' while holding hot pizza",
		"munchies have achieved artificial intelligence status",
		"went to store for munchies... forgot why i went",
		"joint looks like it survived apocalypse... twice",
		"tried to pause my hiccups... seemed logical",
		"dealer's 'dank' smells like lawn clippings",
		"so high i complimented stranger's imaginary dog",
		"tolerance break ended before it technically started",
		"rolled joint with receipt paper... regretted immediately",
		"munchies filing class action lawsuit against my wallet",
		"tried to bookmark real life conversation... muscle memory",
		"dealer's reliability makes unicorns seem plausible",
		"googled 'how to stop time' at 4:20... coincidence?",
		"smoke session has its own gravitational pull",
		"went grocery shopping... bought ingredients for cereal",
		"joint rolling technique involves interpretive dance",
		"tried to mute my own thoughts... no button found",
		"dealer's 'fire' couldn't light wet newspaper",
		"so blazed i thanked my microwave for its patience",
		"tolerance higher than my life expectations... significantly",
		"ordered food delivery to wrong planet... uber confused",
		"joint looks like abstract art's nervous breakdown",
		"tried to screenshot my dreams... technology not there yet",
		"munchies have developed their own supply chain",
		"went to pharmacy high... asked for cough drops... got lectured",
		"joint rolling defies gravity... and common sense",
		"tried to google my own thoughts... search failed",
		"dealer operates on quantum time... everywhere and nowhere"
	};

	public static String START_QUARRYING_MESSAGE = "I feel like training some quarrying now, you coming too?";
}
